# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Unit tests for ``scripts/backfill_contracts.py`` (OMN-10076).

Coverage:
  1. Stubbed Linear client → generates skeleton YAML for a missing ticket.
  2. Existing ``contracts/OMN-XXXX.yaml`` → skipped (idempotent).
  3. Generated YAML round-trips through ``ModelTicketContract`` (OCC model).
  4. Missing ``LINEAR_API_KEY`` → nonzero exit + required error message.
  5. ``--range OMN-123:OMN-200`` → sweep limited to that ID range.
"""

from __future__ import annotations

import importlib
import os
import sys
from typing import TYPE_CHECKING, Any
from unittest.mock import MagicMock, patch

if TYPE_CHECKING:
    from pathlib import Path
    from types import ModuleType

import pytest
import yaml

# sys.path is extended by tests/unit/scripts/conftest.py — no local bootstrap needed.

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_linear_ticket(ticket_id: str = "OMN-150") -> dict[str, Any]:
    """Return a minimal Linear-API-shaped ticket dict."""
    return {
        "id": ticket_id,
        "identifier": ticket_id,
        "title": f"Test ticket {ticket_id}",
        "description": "Auto-generated by backfill test fixture",
        "state": {"name": "Todo"},
        "team": {"key": "OMN"},
    }


def _stub_linear_client(ticket_data: dict[str, Any]) -> MagicMock:
    """Return a MagicMock that mimics the Linear client used by the script."""
    client = MagicMock()
    client.get_issue.return_value = ticket_data
    return client


def _import_backfill() -> ModuleType:
    """Import backfill_contracts from the scripts directory.

    If the module is already cached (e.g., from a previous test in the same
    session), reload it so each test gets a clean state.
    """
    module_name = "backfill_contracts"
    if module_name in sys.modules:
        return importlib.reload(sys.modules[module_name])
    return importlib.import_module(module_name)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def _stub_generate_skeleton_contract(
    ticket_id: str, summary: str, **_kwargs: Any
) -> str:
    """Return a minimal skeleton YAML for testing (avoids OMNI_HOME dependency)."""
    return (
        f"schema_version: '1.0.0'\n"
        f"ticket_id: {ticket_id}\n"
        f"summary: {summary}\n"
        f"is_seam_ticket: false\n"
        f"interface_change: false\n"
        f"interfaces_touched: []\n"
        f"evidence_requirements: []\n"
        f"emergency_bypass:\n"
        f"  enabled: false\n"
        f"  justification: ''\n"
        f"  follow_up_ticket_id: ''\n"
    )


@pytest.mark.unit
def test_generates_skeleton_yaml_for_missing_ticket(tmp_path: Path) -> None:
    """A missing ticket → script writes a skeleton YAML to contracts/."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    # Confirm the file does not exist before the call.
    assert not output_path.exists()

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    # Patch _load_generate_skeleton_contract to avoid OMNI_HOME dependency in CI.
    with patch.object(
        backfill,
        "_load_generate_skeleton_contract",
        return_value=_stub_generate_skeleton_contract,
    ):
        backfill.generate_for_ticket(
            ticket_id=ticket_id,
            contracts_dir=contracts_dir,
            linear_client=stub_client,
            dry_run=False,
        )

    assert output_path.exists(), f"Expected {output_path} to be created"
    content = output_path.read_text(encoding="utf-8")
    assert ticket_id in content


@pytest.mark.unit
def test_skips_existing_contract(tmp_path: Path) -> None:
    """If ``contracts/OMN-XXXX.yaml`` already exists, script must skip it."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    # Pre-write a sentinel contract so the script sees an existing file.
    sentinel_content = "schema_version: '1.0.0'\nticket_id: OMN-150\n"
    output_path.write_text(sentinel_content, encoding="utf-8")
    original_mtime = output_path.stat().st_mtime

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    result = backfill.generate_for_ticket(
        ticket_id=ticket_id,
        contracts_dir=contracts_dir,
        linear_client=stub_client,
        dry_run=False,
    )

    # File must not be overwritten (mtime unchanged, content unchanged).
    assert output_path.stat().st_mtime == original_mtime, (
        "File was modified — idempotency broken"
    )
    assert output_path.read_text(encoding="utf-8") == sentinel_content
    # The return value must signal a skip.
    assert result == "skipped", f"Expected 'skipped', got {result!r}"


@pytest.mark.unit
def test_generated_yaml_validates_against_model_ticket_contract(tmp_path: Path) -> None:
    """Generated YAML must round-trip through ModelTicketContract without error."""
    backfill = _import_backfill()

    # Import the OCC ModelTicketContract (current canonical until core merge lands).
    from onex_change_control.models.model_ticket_contract import ModelTicketContract

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    # Patch _load_generate_skeleton_contract to avoid OMNI_HOME dependency in CI.
    with patch.object(
        backfill,
        "_load_generate_skeleton_contract",
        return_value=_stub_generate_skeleton_contract,
    ):
        backfill.generate_for_ticket(
            ticket_id=ticket_id,
            contracts_dir=contracts_dir,
            linear_client=stub_client,
            dry_run=False,
        )

    assert output_path.exists()
    raw = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    # Must not raise — ValidationError here is a test failure.
    contract = ModelTicketContract.model_validate(raw)
    assert contract.ticket_id == ticket_id


@pytest.mark.unit
def test_missing_linear_api_key_exits_nonzero(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Without LINEAR_API_KEY the script must exit nonzero with a clear message."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()

    # Remove only LINEAR_API_KEY — keep all other env vars intact so that
    # PATH, HOME, TMPDIR and other system variables remain available.
    # Using monkeypatch.delenv with raising=False is safe when the key may
    # not be present in the first place.
    monkeypatch.delenv("LINEAR_API_KEY", raising=False)

    with pytest.raises(SystemExit) as exc_info:
        backfill.main(
            [
                "backfill_contracts.py",
                "--range",
                "OMN-148:OMN-152",
                "--contracts-dir",
                str(contracts_dir),
            ]
        )

    assert exc_info.value.code != 0, (
        "Expected nonzero exit when LINEAR_API_KEY is absent"
    )
    captured = capsys.readouterr()
    combined = captured.out + captured.err
    assert "LINEAR_API_KEY" in combined, (
        "Error output must mention LINEAR_API_KEY; got: " + combined
    )
    assert "required" in combined.lower(), (
        "Error output must indicate it is required; got: " + combined
    )


@pytest.mark.unit
def test_range_argument_limits_sweep(tmp_path: Path) -> None:
    """``--range OMN-123:OMN-200`` must restrict processing to IDs 123-200."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()

    # Track which ticket IDs the script attempts to process.
    processed_ids: list[str] = []

    def _capturing_generate(ticket_id: str, **_kwargs: Any) -> str:
        processed_ids.append(ticket_id)
        return "generated"

    stub_client = MagicMock()

    with (
        patch.dict(os.environ, {"LINEAR_API_KEY": "test-key-stub"}),
        patch.object(backfill, "generate_for_ticket", side_effect=_capturing_generate),
        patch.object(backfill, "_build_linear_client", return_value=stub_client),
    ):
        backfill.main(
            [
                "backfill_contracts.py",
                "--range",
                "OMN-123:OMN-200",
                "--contracts-dir",
                str(contracts_dir),
            ]
        )

    assert processed_ids, "No tickets were processed — range may not be wired"

    # All processed IDs must fall within [123, 200].
    processed_nums = set()
    for tid in processed_ids:
        prefix, num_str = tid.rsplit("-", 1)
        assert prefix == "OMN", f"Unexpected ticket prefix in {tid}"
        num = int(num_str)
        assert 123 <= num <= 200, f"{tid} is outside the declared range OMN-123:OMN-200"
        processed_nums.add(num)

    # The range covers 78 IDs (123..200 inclusive). Every ID in [123, 200]
    # must appear — an implementation that skips IDs would fail this check.
    expected = set(range(123, 201))
    missing = expected - processed_nums
    assert not missing, (
        "Range OMN-123:OMN-200 is incomplete — missing IDs: "
        + ", ".join(f"OMN-{n}" for n in sorted(missing)[:10])
        + (" ..." if len(missing) > 10 else "")
    )
