# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Unit tests for ``scripts/backfill_contracts.py`` (OMN-10075).

These tests are RED by design — the implementation (OMN-10076) does not yet
exist.  Every test is marked ``xfail`` so that CI passes on this branch while
the red state is preserved.  OMN-10076 removes the xfail markers once the
script is implemented.

Coverage:
  1. Stubbed Linear client → generates skeleton YAML for a missing ticket.
  2. Existing ``contracts/OMN-XXXX.yaml`` → skipped (idempotent).
  3. Generated YAML round-trips through ``ModelTicketContract`` (OCC model).
  4. Missing ``LINEAR_API_KEY`` → nonzero exit + required error message.
  5. ``--range OMN-123:OMN-200`` → sweep limited to that ID range.
"""

from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any
from unittest.mock import MagicMock, patch

if TYPE_CHECKING:
    from types import ModuleType

import pytest
import yaml

# ---------------------------------------------------------------------------
# Path bootstrap: add scripts dir so we can import the module under test.
# ---------------------------------------------------------------------------
_SCRIPTS_DIR = Path(__file__).resolve().parents[3] / "scripts"
sys.path.insert(0, str(_SCRIPTS_DIR))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_linear_ticket(ticket_id: str = "OMN-150") -> dict[str, Any]:
    """Return a minimal Linear-API-shaped ticket dict."""
    return {
        "id": ticket_id,
        "identifier": ticket_id,
        "title": f"Test ticket {ticket_id}",
        "description": "Auto-generated by backfill test fixture",
        "state": {"name": "Todo"},
        "team": {"key": "OMN"},
    }


def _stub_linear_client(ticket_data: dict[str, Any]) -> MagicMock:
    """Return a MagicMock that mimics the Linear client used by the script."""
    client = MagicMock()
    client.get_issue.return_value = ticket_data
    return client


def _import_backfill() -> ModuleType:
    """Import backfill_contracts from the scripts directory.

    If the module is already cached (e.g., from a previous test in the same
    session), reload it so each test gets a clean state.
    """
    module_name = "backfill_contracts"
    if module_name in sys.modules:
        return importlib.reload(sys.modules[module_name])
    return importlib.import_module(module_name)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.unit
@pytest.mark.xfail(
    reason="OMN-10076 implements backfill_contracts.py — remove xfail when done",
    strict=True,
)
def test_generates_skeleton_yaml_for_missing_ticket(tmp_path: Path) -> None:
    """A missing ticket → script writes a skeleton YAML to contracts/."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    # Confirm the file does not exist before the call.
    assert not output_path.exists()

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    backfill.generate_for_ticket(
        ticket_id=ticket_id,
        contracts_dir=contracts_dir,
        linear_client=stub_client,
        dry_run=False,
    )

    assert output_path.exists(), f"Expected {output_path} to be created"
    content = output_path.read_text(encoding="utf-8")
    assert ticket_id in content


@pytest.mark.unit
@pytest.mark.xfail(
    reason="OMN-10076 implements backfill_contracts.py — remove xfail when done",
    strict=True,
)
def test_skips_existing_contract(tmp_path: Path) -> None:
    """If ``contracts/OMN-XXXX.yaml`` already exists, script must skip it."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    # Pre-write a sentinel contract so the script sees an existing file.
    sentinel_content = "schema_version: '1.0.0'\nticket_id: OMN-150\n"
    output_path.write_text(sentinel_content, encoding="utf-8")
    original_mtime = output_path.stat().st_mtime

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    result = backfill.generate_for_ticket(
        ticket_id=ticket_id,
        contracts_dir=contracts_dir,
        linear_client=stub_client,
        dry_run=False,
    )

    # File must not be overwritten (mtime unchanged, content unchanged).
    assert output_path.stat().st_mtime == original_mtime, (
        "File was modified — idempotency broken"
    )
    assert output_path.read_text(encoding="utf-8") == sentinel_content
    # The return value must signal a skip.
    assert result == "skipped", f"Expected 'skipped', got {result!r}"


@pytest.mark.unit
@pytest.mark.xfail(
    reason="OMN-10076 implements backfill_contracts.py — remove xfail when done",
    strict=True,
)
def test_generated_yaml_validates_against_model_ticket_contract(tmp_path: Path) -> None:
    """Generated YAML must round-trip through ModelTicketContract without error."""
    backfill = _import_backfill()

    # Import the OCC ModelTicketContract (current canonical until core merge lands).
    from onex_change_control.models.model_ticket_contract import ModelTicketContract

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()
    ticket_id = "OMN-150"
    output_path = contracts_dir / f"{ticket_id}.yaml"

    stub_client = _stub_linear_client(_make_linear_ticket(ticket_id))

    backfill.generate_for_ticket(
        ticket_id=ticket_id,
        contracts_dir=contracts_dir,
        linear_client=stub_client,
        dry_run=False,
    )

    assert output_path.exists()
    raw = yaml.safe_load(output_path.read_text(encoding="utf-8"))
    # Must not raise — ValidationError here is a test failure.
    contract = ModelTicketContract.model_validate(raw)
    assert contract.ticket_id == ticket_id


@pytest.mark.unit
@pytest.mark.xfail(
    reason="OMN-10076 implements backfill_contracts.py — remove xfail when done",
    strict=True,
)
def test_missing_linear_api_key_exits_nonzero(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Without LINEAR_API_KEY the script must exit nonzero with a clear message."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()

    # Strip LINEAR_API_KEY from the environment for this test.
    env_without_key = {k: v for k, v in os.environ.items() if k != "LINEAR_API_KEY"}

    with (
        patch.dict(os.environ, env_without_key, clear=True),
        pytest.raises(SystemExit) as exc_info,
    ):
        backfill.main(
            [
                "backfill_contracts.py",
                "--range",
                "OMN-148:OMN-152",
                "--contracts-dir",
                str(contracts_dir),
            ]
        )

    assert exc_info.value.code != 0, (
        "Expected nonzero exit when LINEAR_API_KEY is absent"
    )
    captured = capsys.readouterr()
    combined = captured.out + captured.err
    assert "LINEAR_API_KEY" in combined, (
        "Error output must mention LINEAR_API_KEY; got: " + combined
    )
    assert "required" in combined.lower(), (
        "Error output must indicate it is required; got: " + combined
    )


@pytest.mark.unit
@pytest.mark.xfail(
    reason="OMN-10076 implements backfill_contracts.py — remove xfail when done",
    strict=True,
)
def test_range_argument_limits_sweep(tmp_path: Path) -> None:
    """``--range OMN-123:OMN-200`` must restrict processing to IDs 123-200."""
    backfill = _import_backfill()

    contracts_dir = tmp_path / "contracts"
    contracts_dir.mkdir()

    # Track which ticket IDs the script attempts to process.
    processed_ids: list[str] = []

    def _capturing_generate(ticket_id: str, **_kwargs: Any) -> str:
        processed_ids.append(ticket_id)
        return "generated"

    stub_client = MagicMock()

    with (
        patch.dict(os.environ, {"LINEAR_API_KEY": "test-key-stub"}),
        patch.object(backfill, "generate_for_ticket", side_effect=_capturing_generate),
        patch.object(backfill, "_build_linear_client", return_value=stub_client),
    ):
        backfill.main(
            [
                "backfill_contracts.py",
                "--range",
                "OMN-123:OMN-200",
                "--contracts-dir",
                str(contracts_dir),
            ]
        )

    assert processed_ids, "No tickets were processed — range may not be wired"

    # All processed IDs must fall within [123, 200].
    for tid in processed_ids:
        prefix, num_str = tid.rsplit("-", 1)
        assert prefix == "OMN", f"Unexpected ticket prefix in {tid}"
        num = int(num_str)
        assert 123 <= num <= 200, f"{tid} is outside the declared range OMN-123:OMN-200"

    # Sanity check: the range covers 78 IDs (123..200 inclusive).
    assert len(processed_ids) <= 78, (
        f"Processed {len(processed_ids)} IDs but range OMN-123:OMN-200 has at most 78"
    )
