# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Wrapper: scaffold OCC stubs, commit, push, open a PR.

Usage:
    uv run scripts/auto_scaffold_and_pr.py OMN-9582 --title "My ticket"
    uv run scripts/auto_scaffold_and_pr.py OMN-9582 --title "Title" \
        --description "..."
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def _run(
    cmd: list[str],
    *,
    check: bool = True,
    cwd: str | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603
        cmd,
        capture_output=True,
        text=True,
        check=check,
        cwd=cwd,
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Scaffold OCC contract stubs and open a PR",
    )
    parser.add_argument("ticket_id", help="Linear ticket ID (e.g., OMN-9582)")
    parser.add_argument("--title", default=None, help="Ticket title")
    parser.add_argument(
        "--description",
        default="",
        help="Ticket description for DoD extraction",
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help="Path to onex_change_control repo root",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate files but skip git operations and PR",
    )
    args = parser.parse_args(argv)

    repo_root = (
        Path(args.repo_root)
        if args.repo_root
        else Path(__file__).resolve().parent.parent
    )
    ticket_id = args.ticket_id.upper()
    title = args.title or ticket_id

    scaffold_script = repo_root / "scripts" / "auto_scaffold_contract.py"

    scaffold_cmd = [
        sys.executable,
        str(scaffold_script),
        ticket_id,
        "--title",
        title,
        "--repo-root",
        str(repo_root),
    ]
    if args.description:
        scaffold_cmd.extend(["--description", args.description])

    result = _run(scaffold_cmd, check=False)
    print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        sys.exit(result.returncode)

    if args.dry_run:
        print("\n[dry-run] skipping git commit + PR")
        return

    branch_name = f"jonah/{ticket_id.lower()}-auto-occ-stubs"

    _run(["git", "add", "contracts/", "drift/dod_receipts/"], cwd=str(repo_root))

    status = _run(["git", "status", "--porcelain"], cwd=str(repo_root))
    if not status.stdout.strip():
        print("No changes to commit (files may already exist).")
        return

    commit_msg = f"chore({ticket_id}): auto-scaffold OCC contract stubs"
    _run(["git", "commit", "-m", commit_msg], cwd=str(repo_root))
    _run(
        ["git", "push", "-u", "origin", "HEAD:" + branch_name],
        cwd=str(repo_root),
    )

    pr_result = _run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            commit_msg,
            "--body",
            f"Auto-scaffolded OCC contract stubs for {ticket_id}.\n\n"
            f"Generated by `scripts/auto_scaffold_contract.py`.",
            "--base",
            "main",
            "--head",
            branch_name,
        ],
        check=False,
        cwd=str(repo_root),
    )

    if pr_result.returncode == 0:
        print(f"\nPR created: {pr_result.stdout.strip()}")
    else:
        print(
            f"\n[warn] PR creation failed: {pr_result.stderr.strip()}", file=sys.stderr
        )


if __name__ == "__main__":
    main()
