name: Setup Poetry
description: Setup Python, cache dependencies, install Poetry, and install project dependencies

inputs:
  python-version:
    description: Python version to use
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.0  # Pinned for reproducibility
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction
